

development:
      host: localhost
      adapter: mysql
      database: fedena_development
      port: 3306
      username: root




      password: root

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: root

production:
      host: localhost
      adapter: mysql
      database: fedena_production
      port: 3306
      username: root
      password: root
cucumber:
  <<: *test
